name: nix flake ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: nix flake check
        run: nix flake check

      - name: check formatting with alejandra
        run: nix run nixpkgs#alejandra -- --check .

      - name: lint with nil
        run: nix run nixpkgs#nil -- check .
